homeassistant:
  name: Hjemme
  latitude: 63.431148449714215
  longitude: 10.45704723361333
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"
  external_url: "https://home.dagstuan.com"
  internal_url: "http://nas.local:8123"
  packages: !include_dir_merge_named packages/
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

api:

nordpool:

recorder:
  purge_keep_days: 20
  commit_interval: 5
  include:
    domains:
      - light
      - switch
      - media_player
      - climate
      - weather
      - person
      - binary_sensor
      - input_select
    entities:
      - sensor.outdoor_temperature
      - device_tracker.ios_dag
      - device_tracker.ios_ingvild
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.time*
      - sensor.electricity*
      - sensor.mill*
      - sensor.climate_*
      - sensor.pi_hole*
      - sensor.rbr750*
      - sensor.speedtest*
      - sensor.kontor*
      - sensor.soverom*
      - sensor.stua*
      - sensor.climate_*
      - sensor.tautulli*
      - sensor.nordpool*
      - sensor.powersaving*
      - sensor.han*
      - sensor.home_consumption*
      - sensor.varmtvannsbereder*
      - sensor.gang*
      - binary_sensor.pingu*
      - sensor.pingu*
      - number.pingu*
      - device_tracker.pingu*
      - switch.pingu*
      - sensor.ev_charger*
      - sensor.other_current_power
      - sensor.ev_smart_charging_charging
      - sensor.ev_charger_consumption*
      - number.ev_charger_installation_available_current
      - sensor.non_ev*
      - sensor.kaffetrakter*
      - sensor.vaskemaskin*
  db_url: !secret mariadb_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.9.8.2/32

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - unique_id: "kjokkenspotter"
      name: "Spotter"
      state_topic: "kjokken/spots/status"
      command_topic: "kjokken/spots/switch"
      brightness_state_topic: 'kjokken/spots/brightness'
      brightness_command_topic: 'kjokken/spots/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

    - name: "Øy"
      unique_id: "kjokkenoy"
      state_topic: "kjokken/oy/status"
      command_topic: "kjokken/oy/switch"
      brightness_state_topic: 'kjokken/oy/brightness'
      brightness_command_topic: 'kjokken/oy/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

google_assistant:
  project_id: home-assistant-34e7d
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - light
    - climate
  entity_config:
    switch.kaffetrakter:
      name: "Kaffetrakter"
      expose: true
      aliases:
        - Kaffetrakteren
        - Kaffen
    light.spotter:
      name: "Spotter"
      expose: true
      aliases:
        - Spotlights
        - Kjøkkenspotter
        - Downlights
    light.oy:
      name: "Øy"
      expose: true
      aliases:
        - Kjøkkenøy
        - Øya
        - Øy
        - Mikro
        - Mikrobølgeovn
        - Kjøkkenøya
        - Hengelys

input_boolean:
  dag_home:
    name: Dag home
  ingvild_home:
    name: Ingvild home
  lights_dimmed_by_movie_mode:
    name: Lights were dimmed by movie mode
  alarm_triggered_today:
    name: Alarm triggered today
  vaskemaskin_running:
    name: Vaskemaskin running

input_text:
  stue_bryter_helper_last_controller_event:
    name: stue_bryter_helper_last_controller_event
  soverom_bryter_helper_last_controller_event:
    name: soverom_bryter_helper_last_controller_event

input_number:
  kwh_limit:
    name: kWh limit
    min: 0
    max: 10
    step: 0.05
    unit_of_measurement: kWh
    mode: box
  power_limit:
    name: Power limit
    min: 0
    max: 10000
    unit_of_measurement: W
    mode: box

template:
  - sensor:
    - name: Outdoor temperature
      unique_id: outdoor_temperature
      state: "{{ state_attr('weather.home', 'temperature') }}"
      unit_of_measurement: "°C"
      state_class: measurement
    - name: Other current power
      unique_id: other_current_power
      state: >
        {{
          [((states('sensor.han_sensor_power')| float(0)) -
          (states('sensor.ev_charger_charge_power') | float(0)) -
          (states('sensor.varmtvannsbereder_power') | float(0)) -
          (states('sensor.mill_kontor_current_power') | float(0)) -
          (states('sensor.mill_stua_current_power') | float(0)) -
          (states('sensor.mill_soverom_current_power') | float(0)) -
          (states('sensor.climate_bad_current_power') | float(0)))
          | round(3), 0] | max
        }}
      unit_of_measurement: W
      state_class: measurement
      device_class: power
    - name: Predicted consumption current hour
      unique_id: predicted_consumption_current_hour
      state: >-
        {%- set now=now() -%}
        {%- set time_left_current_hour=(1 - now.minute / 60 - now.second / 3600)  -%}
        {%- set consumption_current_hour=states('sensor.home_consumption_hourly') | float(0)  -%}
        {%- set han_sensor_power_moving_avg_10m=states('sensor.han_sensor_power_moving_avg_10m') | float(0) -%}
        {%- set predicted_consumption_rest_of_hour=(han_sensor_power_moving_avg_10m/1000.0)*time_left_current_hour -%}

        {{ consumption_current_hour + predicted_consumption_rest_of_hour }}
      state_class: measurement
      unit_of_measurement: kWh
  - binary_sensor:
    - name: Varmtvannsbereder drawing power
      unique_id: varmtvannsbereder_drawing_power
      state: "{{ states('sensor.varmtvannsbereder_power') | float(0) > 1 }}"

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'

  - platform: history_stats
    name: Varmtvannsbereder on today
    entity_id: binary_sensor.varmtvannsbereder_drawing_power
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: nordpool
    region: NO3
    precision: 3
    price_type: kWh
    currency: NOK
    additional_costs: >-
      {%  set price_with_stromstotte = max(current_price - 0.9125, 0) %}
      {%  set s = {
          "kapasitetsledd_maaned_kost": 239,
          "energiselskap_maaned_kost": 0,
          "energiledd_vinter_dag_inkl_avg_og_mva": 0.3989,
          "energiledd_vinter_natt_inkl_avg_og_mva": 0.2651,
          "energiledd_sommer_dag_inkl_avg_og_mva": 0.5018,
          "energiledd_sommer_natt_inkl_avg_og_mva": 0.3593,
          "stromstotte": price_with_stromstotte * 0.9
        }
      %}
      {% set now = now() %}
      {% if now.month >= 1 and now.month <= 3 %}
        {% if now.hour >= 6 and now.hour <= 22 %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_vinter_dag_inkl_avg_og_mva-s.stromstotte|float}}
        {% else %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_vinter_natt_inkl_avg_og_mva-s.stromstotte|float}}
        {% endif %}
      {% else %}
        {% if now.hour >= 6 and now.hour <= 22 %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_sommer_dag_inkl_avg_og_mva-s.stromstotte|float}}
        {% else %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_sommer_natt_inkl_avg_og_mva-s.stromstotte|float}}
        {% endif %}
      {% endif %}

  - platform: integration
    source: sensor.han_sensor_power
    unique_id: home_consumption
    name: Home consumption
    method: left
    unit_prefix: k
    unit_time: h

  - platform: filter
    entity_id: sensor.han_sensor_power
    name: Han sensor power moving avg 10m
    unique_id: han_sensor_power_moving_avg_10m
    filters:
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:10"
        precision: 2

  - platform: filter
    entity_id: sensor.han_sensor_power
    name: Han sensor power moving avg 20m
    unique_id: han_sensor_power_moving_avg_20m
    filters:
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:20"
        precision: 2

utility_meter:
  home_consumption_hourly:
    source: sensor.home_consumption
    name: Home consumption hourly
    cycle: hourly
  home_consumption_daily:
    source: sensor.home_consumption
    name: Home consumption daily
    cycle: daily
  home_consumption_monthly:
    source: sensor.home_consumption
    name: Home consumption monthly
    cycle: monthly
  home_consumption_yearly:
    source: sensor.home_consumption
    name: Home consumption yearly
    cycle: daily
  home_consumption_cost_daily:
    source: sensor.home_consumption_cost
    name: Home consumption cost daily
    cycle: daily
  home_consumption_cost_monthly:
    source: sensor.home_consumption_cost
    name: Home consumption cost monthly
    cycle: monthly
  home_consumption_cost_yearly:
    source: sensor.home_consumption_cost
    name: Home consumption cost yearly
    cycle: yearly

rest_command:
  healthcheck_io:
    url: https://hc-ping.com/b54bbee3-7933-4e84-b883-b8af56716670

logger:
  default: warning
  logs:
    custom_components.pyscript: warning
    custom_components.pyscript.file: warning
    # homeassistant.components.recorder: debug
