homeassistant:
  name: Hjemme
  latitude: 63.431148449714215
  longitude: 10.45704723361333
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"
  external_url: "https://home.dagstuan.com"
  internal_url: "http://nas.local:8123"
  packages: !include_dir_merge_named packages/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

api:

nordpool:

recorder:
  purge_keep_days: 14
  commit_interval: 10
  include:
    domains:
      - automation
      - light
      - switch
      - media_player
      - climate
      - weather
      - person
      - binary_sensor
      - input_select
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.time*
      - sensor.electricity*
      - sensor.mill*
      - sensor.climate_*
      - sensor.outdoor_temperature
      - sensor.pi_hole*
      - sensor.rbr750_gateway*
      - sensor.speedtest*
      - sensor.kontor*
      - sensor.soverom*
      - sensor.stua*
      - sensor.climate_*
      - sensor.tautulli*
      - device_tracker.ios_dag
      - device_tracker.ios_ingvild
      - sensor.nordpool*
      - sensor.powersaving*
      - sensor.han*
      - sensor.home_consumption*
      - sensor.varmtvannsbereder*
      - sensor.gang*
  db_url: !secret mariadb_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.9.8.2/32

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - unique_id: "kjokkenspotter"
      name: "Spotter"
      state_topic: "kjokken/spots/status"
      command_topic: "kjokken/spots/switch"
      brightness_state_topic: 'kjokken/spots/brightness'
      brightness_command_topic: 'kjokken/spots/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

    - name: "Øy"
      unique_id: "kjokkenoy"
      state_topic: "kjokken/oy/status"
      command_topic: "kjokken/oy/switch"
      brightness_state_topic: 'kjokken/oy/brightness'
      brightness_command_topic: 'kjokken/oy/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

google_assistant:
  project_id: home-assistant-34e7d
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - light
    - climate
  entity_config:
    light.spotter:
      name: "Spotter"
      expose: true
      aliases:
        - Spotlights
        - Kjøkkenspotter
        - Downlights
    light.oy:
      name: "Øy"
      expose: true
      aliases:
        - Kjøkkenøy
        - Øya
        - Øy
        - Mikro
        - Mikrobølgeovn
        - Kjøkkenøya
        - Hengelys

input_boolean:
  dag_home:
    name: Dag home
  ingvild_home:
    name: Ingvild home
  lights_dimmed_by_movie_mode:
    name: Lights were dimmed by movie mode
  alarm_triggered_today:
    name: Alarm triggered today
  dummy_heater_on:
    name: Heater power ON

input_text:
  stue_bryter_helper_last_controller_event:
    name: stue_bryter_helper_last_controller_event
  soverom_bryter_helper_last_controller_event:
    name: soverom_bryter_helper_last_controller_event

input_select:
  kontor_temperature_mode:
    options:
      - comfort
      - sleep
      - away
      - vacation
    icon: mdi:target
  stua_temperature_mode:
    options:
      - comfort
      - sleep
      - away
      - vacation
    icon: mdi:target
  soverom_temperature_mode:
    options:
      - comfort
      - sleep
      - away
      - vacation
    icon: mdi:target

input_number:
  climate_kontor_window_open_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_kontor_comfort_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_kontor_sleep_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_kontor_away_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_kontor_vacation_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_stua_window_open_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_stua_comfort_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_stua_sleep_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_stua_away_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_stua_vacation_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_soverom_window_open_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_soverom_comfort_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_soverom_sleep_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_soverom_away_temperature:
    min: 0
    max: 40
    step: 0.5
  climate_soverom_vacation_temperature:
    min: 0
    max: 40
    step: 0.5

template:
  - sensor:
    - name: Climate kontor hvac action
      state: "{{ state_attr('climate.kontor', 'hvac_action') }}"
    - name: climate_kontor_heating_state_graph
      unit_of_measurement: '°C'
      state: >
        {% if is_state_attr ('climate.kontor','hvac_action', 'heating') %}
        {{ state_attr('climate.kontor', 'current_temperature') }}
        {% else %}
        0
        {% endif %}
    - name: Climate stua hvac action
      state: "{{ state_attr('climate.stua', 'hvac_action') }}"
    - name: climate_stua_heating_state_graph
      unit_of_measurement: '°C'
      state: >
        {% if is_state_attr ('climate.stua','hvac_action', 'heating') %}
        {{ state_attr('climate.stua', 'current_temperature') }}
        {% else %}
        0
        {% endif %}
    - name: Climate soverom hvac action
      state: "{{ state_attr('climate.soverom', 'hvac_action') }}"
    - name: climate_soverom_heating_state_graph
      unit_of_measurement: '°C'
      state: >
        {% if is_state_attr ('climate.soverom','hvac_action', 'heating') %}
        {{ state_attr('climate.soverom', 'current_temperature') }}
        {% else %}
        0
        {% endif %}
    - name: Outdoor temperature
      state: "{{ state_attr('weather.home', 'temperature') }}"
      unit_of_measurement: "°C"
      state_class: measurement

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_free
      - type: disk_free
      - type: processor_use

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: history_stats
    name: Climate kontor heating today
    entity_id: sensor.climate_kontor_hvac_action
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Climate stua heating today
    entity_id: sensor.climate_stua_hvac_action
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Climate soverom heating today
    entity_id: sensor.climate_soverom_hvac_action
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Varmtvannsbereder on today
    entity_id: switch.varmtvannsbereder
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: nordpool
    region: "Tr.heim"
    precision: 3
    price_type: kWh
    currency: NOK
    additional_costs: '{% set s = {
  "kapasitet_2_5_arlig_kost": 1530,
  "tibber_maned_kost": 39,
  "energiledd_dag": 0.15750,
  "energiledd_natt": 0.07875,
  "enova": 0.0125,
  "spotpris": 0.01
}
%}
{% if now().hour >=6 and now().hour <23 %}
  {{((s.kapasitet_2_5_arlig_kost+(12*s.tibber_maned_kost))/365/24)+s.energiledd_dag+s.enova+s.spotpris|float}}
{% else %}
  {{((s.kapasitet_2_5_arlig_kost+(12*s.tibber_maned_kost))/365/24)+s.energiledd_natt+s.enova+s.spotpris|float}}
{% endif %}'

  - platform: integration
    source: sensor.mill_kontor_current_power
    unique_id: mill_kontor_energy
    name: Mill kontor energy
    method: left
    unit_prefix: k
  - platform: integration
    source: sensor.mill_stua_current_power
    unique_id: mill_stua_energy
    name: Mill stua energy
    method: left
    unit_prefix: k
  - platform: integration
    source: sensor.mill_soverom_current_power
    unique_id: mill_soverom_energy
    name: Mill soverom energy
    method: left
    unit_prefix: k

  - platform: integration
    source: sensor.han_sensor_power
    unique_id: home_consumption
    name: Home consumption
    method: left
    unit_prefix: k
    unit_time: h

utility_meter:
  home_consumption_hourly:
    source: sensor.home_consumption
    name: Home consumption hourly
    cycle: hourly
  kontor_heating_time_daily:
    source: sensor.climate_kontor_heating_today
    name: Kontor Heating Time Daily
    cycle: daily
  kontor_heating_time_weekly:
    source: sensor.climate_kontor_heating_today
    name: Kontor Heating Time Weekly
    cycle: weekly
  kontor_heating_time_monthly:
    source: sensor.climate_kontor_heating_today
    name: Kontor Heating Time Monthly
    cycle: monthly
  kontor_heating_time_yearly:
    source: sensor.climate_kontor_heating_today
    name: Kontor Heating Time Yearly
    cycle: yearly
  stua_heating_time_daily:
    source: sensor.climate_stua_heating_today
    name: Stua Heating Time Daily
    cycle: daily
  stua_heating_time_weekly:
    source: sensor.climate_stua_heating_today
    name: Stua Heating Time Weekly
    cycle: weekly
  stua_heating_time_monthly:
    source: sensor.climate_stua_heating_today
    name: Stua Heating Time Monthly
    cycle: monthly
  stua_heating_time_yearly:
    source: sensor.climate_stua_heating_today
    name: Stua Heating Time Yearly
    cycle: yearly
  soverom_heating_time_weekly:
    source: sensor.climate_soverom_heating_today
    name: Soverom Heating Time Weekly
    cycle: weekly
  soverom_heating_time_monthly:
    source: sensor.climate_soverom_heating_today
    name: Soverom Heating Time Monthly
    cycle: monthly
  soverom_heating_time_yearly:
    source: sensor.climate_soverom_heating_today
    name: Soverom Heating Time Yearly
    cycle: yearly

rest_command:
  healthcheck_io:
    url: https://hc-ping.com/b54bbee3-7933-4e84-b883-b8af56716670

#logger:
#  default: debug
