homeassistant:
  name: Hjemme
  latitude: 63.431148449714215
  longitude: 10.45704723361333
  unit_system: metric
  time_zone: Europe/Oslo
  country: "NO"
  external_url: "https://home.dagstuan.com"
  internal_url: "http://nas.local:8123"
  packages: !include_dir_merge_named packages/
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

api:

nordpool:

recorder:
  purge_keep_days: 14
  commit_interval: 10
  include:
    domains:
      - automation
      - light
      - switch
      - media_player
      - climate
      - weather
      - person
      - binary_sensor
      - input_select
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.time*
      - sensor.electricity*
      - sensor.mill*
      - sensor.climate_*
      - sensor.outdoor_temperature
      - sensor.pi_hole*
      - sensor.rbr750_gateway*
      - sensor.speedtest*
      - sensor.kontor*
      - sensor.soverom*
      - sensor.stua*
      - sensor.climate_*
      - sensor.tautulli*
      - device_tracker.ios_dag
      - device_tracker.ios_ingvild
      - sensor.nordpool*
      - sensor.powersaving*
      - sensor.han*
      - sensor.home_consumption*
      - sensor.varmtvannsbereder*
      - sensor.gang*
  db_url: !secret mariadb_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.9.8.2/32

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - unique_id: "kjokkenspotter"
      name: "Spotter"
      state_topic: "kjokken/spots/status"
      command_topic: "kjokken/spots/switch"
      brightness_state_topic: 'kjokken/spots/brightness'
      brightness_command_topic: 'kjokken/spots/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

    - name: "Øy"
      unique_id: "kjokkenoy"
      state_topic: "kjokken/oy/status"
      command_topic: "kjokken/oy/switch"
      brightness_state_topic: 'kjokken/oy/brightness'
      brightness_command_topic: 'kjokken/oy/brightness/set'
      payload_off: "OFF"
      on_command_type: 'brightness'

google_assistant:
  project_id: home-assistant-34e7d
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - light
    - climate
  entity_config:
    light.spotter:
      name: "Spotter"
      expose: true
      aliases:
        - Spotlights
        - Kjøkkenspotter
        - Downlights
    light.oy:
      name: "Øy"
      expose: true
      aliases:
        - Kjøkkenøy
        - Øya
        - Øy
        - Mikro
        - Mikrobølgeovn
        - Kjøkkenøya
        - Hengelys

input_boolean:
  dag_home:
    name: Dag home
  ingvild_home:
    name: Ingvild home
  lights_dimmed_by_movie_mode:
    name: Lights were dimmed by movie mode
  alarm_triggered_today:
    name: Alarm triggered today

input_text:
  stue_bryter_helper_last_controller_event:
    name: stue_bryter_helper_last_controller_event
  soverom_bryter_helper_last_controller_event:
    name: soverom_bryter_helper_last_controller_event

template:
  - sensor:
    - name: Outdoor temperature
      state: "{{ state_attr('weather.home', 'temperature') }}"
      unit_of_measurement: "°C"
      state_class: measurement
  - binary_sensor:
    - name: Varmtvannsbereder drawing power
      unique_id: varmtvannsbereder_drawing_power
      state: "{{ states('sensor.varmtvannsbereder_power') |  float > 1 }}"

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_free
      - type: disk_free
      - type: processor_use

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: history_stats
    name: Varmtvannsbereder on today
    entity_id: binary_sensor.varmtvannsbereder_drawing_power
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: nordpool
    region: "Tr.heim"
    precision: 3
    price_type: kWh
    currency: NOK
    additional_costs: >-
      {%  set price_with_stromstotte = max(current_price - 0.9125, 0) %}
      {%  set s = {
          "kapasitetsledd_maaned_kost": 225,
          "energiselskap_maaned_kost": 0,
          "energiledd_vinter_dag_inkl_avg_og_mva": 0.3989,
          "energiledd_vinter_natt_inkl_avg_og_mva": 0.2651,
          "energiledd_summer_dag_inkl_avg_og_mva": 0.4855,
          "energiledd_summer_natt_inkl_avg_og_mva": 0.3518,
          "stromstotte": price_with_stromstotte * 0.9
        }
      %}
      {% set now = now() %}
      {% if now.month >= 1 and now.month <= 3 %}
        {% if now.hour >= 6 and now.hour <= 22 %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_vinter_dag_inkl_avg_og_mva-s.stromstotte|float}}
        {% else %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_vinter_natt_inkl_avg_og_mva-s.stromstotte|float}}
        {% endif %}
      {% else %}
        {% if now.hour >= 6 and now.hour <= 22 %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_summer_dag_inkl_avg_og_mva-s.stromstotte|float}}
        {% else %}
            {{(((s.kapasitetsledd_maaned_kost+s.energiselskap_maaned_kost)*12)/365/24)+s.energiledd_summer_natt_inkl_avg_og_mva-s.stromstotte|float}}
        {% endif %}
      {% endif %}

  - platform: integration
    source: sensor.han_sensor_power
    unique_id: home_consumption
    name: Home consumption
    method: left
    unit_prefix: k
    unit_time: h

utility_meter:
  home_consumption_hourly:
    source: sensor.home_consumption
    name: Home consumption hourly
    cycle: hourly
  home_consumption_daily:
    source: sensor.home_consumption
    name: Home consumption daily
    cycle: daily
  home_consumption_monthly:
    source: sensor.home_consumption
    name: Home consumption monthly
    cycle: monthly
  home_consumption_yearly:
    source: sensor.home_consumption
    name: Home consumption yearly
    cycle: daily
  home_consumption_cost_daily:
    source: sensor.home_consumption_cost
    name: Home consumption cost daily
    cycle: daily
  home_consumption_cost_monthly:
    source: sensor.home_consumption_cost
    name: Home consumption cost monthly
    cycle: monthly
  home_consumption_cost_yearly:
    source: sensor.home_consumption_cost
    name: Home consumption cost yearly
    cycle: yearly

rest_command:
  healthcheck_io:
    url: https://hc-ping.com/b54bbee3-7933-4e84-b883-b8af56716670

#logger:
#  default: debug
